from bs4 import BeautifulSoup

with open("ecologicalpyramid.html","r") as ecological_pyramid:
  soup = BeautifulSoup(ecological_pyramid,"lxml")
"""
producer_entries = soup.find("ul")
print(producer_entries.attrs)
print(producer_entries)
print(producer_entries.string)
list_entry = soup.find("li")
print(type(list_entry))
print(list_entry)
print(list_entry.attrs)
#print(list_entry.attrs['class']['producerlist'])
print(list_entry.name)
#print(list_entry.name.string)
#print(list_entry['producerlist'])

div_entries = soup.find("div")
print(div_entries.attrs)
print(div_entries.string)
"""
some_text = soup.find(text="plants")
print(type(some_text))
print(some_text)
#producer = soup.find(id="producers")
#print(producer)
print('1.')
primaryconsumer = soup.find(id="primaryconsumers")
print(primaryconsumer)
print('2.')
primaryconsumer_1 = soup.find(attrs={'id':'primaryconsumers'})
print(primaryconsumer_1)
print('--------------------')
primaryconsumerlist = soup.find(attrs={'class':'primaryconsumerlist'})
print(primaryconsumerlist)
print('3.')
first_primaryconsumer = soup.find(class_='name')
print(first_primaryconsumer)
print('4.')
divname = soup.find("div",class_="qname")
print(divname)
print('5.')
pname = soup.find("li",class_="qname")
print(pname)
